# ---------------------------------------------------------------
# 方案设置
# ---------------------------------------------------------------

scheme: Gemini

# ---------------------------------------------------------------
# 站点信息设置
# ---------------------------------------------------------------

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

# ---------------------------------------------------------------
# 菜单设置
# ---------------------------------------------------------------

menu:
  安装: /installation/ || fa fa-download
  开始使用:
    default: /started/ || fa fa-bell
    配置: /configuration/ || fa fa-balance-scale
    命令: /commands/ || fa fa-keyboard
  基本操作:
    default: /usage/ || fa fa-pen
    Front Matter: /front-matter/ || fa fa-anchor
    标签插件: /tag-plugins/ || fa fa-tags
    资源文件夹: /asset-folders/ || fa fa-folder
    数据文件: /data-files/ || fa fa-file
    服务器: /server/ || fa fa-server
    生成文件: /generating/ || fa fa-box
  部署: /deployment/ || fa fa-project-diagram
  自定义:
    default: /customization/ || fa fa-cog
    永久链接: /permalinks/ || fa fa-link
    主题: /themes/ || fa fa-tshirt
    模板: /templates/ || fa fa-layer-group
    国际化: /internationalization/ || fa fa-globe
    代码高亮: /syntax-highlight/ || fa fa-code
    插件: /plugins/ || fa fa-tools

# ---------------------------------------------------------------
# 侧边栏设置
# 参见：https://mopsite.github.io/next/theme-settings/sidebar/
# ---------------------------------------------------------------

# 侧边栏头像
avatar:
  # 设置链接以替换默认图像
  url: /images/avatar.svg
  # 如果为 true，头像将显示为圆形
  rounded: true

# 侧边栏显示文章 / 分类 / 标签
site_state: false

# 侧边栏链接管理
links_settings:
  icon:
  title:
  # 链接布局，可用值：block | inline
  layout: block

links:
  Git: https://mopsite.github.io/git
  NexT: https://mopsite.github.io/next
  FontAwesome: https://mopsite.github.io/fontawesome

# ---------------------------------------------------------------
# 页脚设置
# 参见：https://mopsite.github.io/next/theme-settings/footer/
# ---------------------------------------------------------------

footer:
  # 建站年份，如果不设置，则只显示当前年份
  since: 2021

  # 年份和版权之间的图标
  icon:
    # 如果想要动画图标，设置为true
    animated: true

  # 是否显示强力驱动
  powered: false

# ---------------------------------------------------------------
# 其他设置
# 参见：https://mopsite.github.io/next/theme-settings/miscellaneous/
# ---------------------------------------------------------------

codeblock:
  # 代码块高亮主题
  # 所有可用的主题：https://theme-next.js.org/highlight/
  theme:
    light: agate
    dark: agate
  # 代码块复制按钮
  copy_button:
    enable: true
    # 可用值：default | flat | mac
    style: mac

back2top:
  # 返回顶部按钮中显示滚动百分比
  scrollpercent: true

# 阅读进度条
reading_progress:
  enable: true
  # 可用值：top | bottom
  position: bottom

# ---------------------------------------------------------------
# 第三方插件和服务设置
# 参见：https://mopsite.github.io/next/third-party-services/
# 更多插件：https://github.com/next-theme/awesome-next
# 你可能需要安装相应的依赖包
# ---------------------------------------------------------------

# 为你的网站提供快速浏览
# 更多信息：https://github.com/next-theme/pjax
pjax: true

# FancyBox 是一款用来缩放图片的工具
# 更多信息：https://fancyapps.com/fancybox/
fancybox: true

# 盘古之白，用于在中英文之间自动插入空格
# 更多信息：https://github.com/vinta/pangu.js
pangu: true

# 快速链接
# 更多信息：https://getquick.link
quicklink:
  enable: true

# ---------------------------------------------------------------
# 搜索服务
# ---------------------------------------------------------------

# 本地搜索
# 依赖包：https://github.com/next-theme/hexo-generator-searchdb
# 参见：https://mopsite.github.io/next/third-party-services/local-search/

local_search:
  enable: true

# ---------------------------------------------------------------
# 标签插件设置
# 参见：https://mopsite.github.io/next/tag-plugins/
# ---------------------------------------------------------------

# 便签标签
note:
  # 便签标签样式值
  style: flat
  icons: true

# 绘图标签
mermaid:
  enable: true
